<?php

declare(strict_types=1);

namespace Vatly\Laravel\Tests\Models;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Vatly\Laravel\Models\Order;
use Vatly\Laravel\Models\OrderLine;
use Vatly\Laravel\Models\Subscription;
use Vatly\Laravel\Tests\BaseTestCase;

class SubscriptionTest extends BaseTestCase
{
    use RefreshDatabase;

    public function test_it_implements_subscription_interface_getters()
    {
        $user = User::factory()->create([
            'vatly_id' => 'customer_456',
        ]);

        $subscription = Subscription::create([
            'owner_type' => $user->getMorphClass(),
            'owner_id' => $user->getKey(),
            'vatly_id' => 'sub_789',
            'plan_id' => 'plan_abc',
            'name' => 'Basic Plan',
            'type' => 'basic',
            'quantity' => 1,
        ]);

        $this->assertEquals('sub_789', $subscription->getVatlyId());
        $this->assertEquals('basic', $subscription->getType());
        $this->assertEquals('plan_abc', $subscription->getPlanId());
        $this->assertEquals('Basic Plan', $subscription->getName());
        $this->assertEquals(1, $subscription->getQuantity());
        $this->assertNull($subscription->getEndsAt());
    }

    public function test_it_identifies_active_subscriptions()
    {
        $user = User::factory()->create([
            'vatly_id' => 'customer_789',
        ]);

        $subscription = Subscription::create([
            'owner_type' => $user->getMorphClass(),
            'owner_id' => $user->getKey(),
            'vatly_id' => 'sub_active',
            'plan_id' => 'plan_xyz',
            'name' => 'Active Plan',
            'type' => Subscription::DEFAULT_TYPE,
            'quantity' => 1,
            'ends_at' => null,
        ]);

        $this->assertTrue($subscription->isActive());
        $this->assertFalse($subscription->isCancelled());
        $this->assertFalse($subscription->isOnGracePeriod());
    }

    public function test_it_identifies_canceled_subscriptions()
    {
        $user = User::factory()->create([
            'vatly_id' => 'customer_canceled',
        ]);

        $subscription = Subscription::create([
            'owner_type' => $user->getMorphClass(),
            'owner_id' => $user->getKey(),
            'vatly_id' => 'sub_canceled',
            'plan_id' => 'plan_xyz',
            'name' => 'Canceled Plan',
            'type' => Subscription::DEFAULT_TYPE,
            'quantity' => 1,
            'ends_at' => now()->subDay(), // Ended in the past
        ]);

        $this->assertFalse($subscription->isActive());
        $this->assertTrue($subscription->isCancelled());
        $this->assertFalse($subscription->isOnGracePeriod());
    }

    public function test_it_identifies_subscriptions_on_grace_period()
    {
        $user = User::factory()->create([
            'vatly_id' => 'customer_grace',
        ]);

        $subscription = Subscription::create([
            'owner_type' => $user->getMorphClass(),
            'owner_id' => $user->getKey(),
            'vatly_id' => 'sub_grace',
            'plan_id' => 'plan_xyz',
            'name' => 'Grace Period Plan',
            'type' => Subscription::DEFAULT_TYPE,
            'quantity' => 1,
            'ends_at' => now()->addWeek(), // Ends in the future
        ]);

        $this->assertTrue($subscription->isActive()); // Still active during grace period
        $this->assertTrue($subscription->isCancelled()); // But is cancelled
        $this->assertTrue($subscription->isOnGracePeriod());
    }

    public function test_orders_returns_the_subscriptions_renewal_orders(): void
    {
        $subscription = Subscription::create([
            'vatly_id' => 'subscription_orders',
            'plan_id' => 'plan_xyz',
            'name' => 'Pro Plan',
            'type' => Subscription::DEFAULT_TYPE,
            'quantity' => 1,
        ]);

        // Two orders generated by this subscription (initial + renewal).
        $initial = Order::create(['vatly_id' => 'ord_initial', 'status' => 'paid', 'total' => 9900, 'currency' => 'EUR']);
        $renewal = Order::create(['vatly_id' => 'ord_renewal', 'status' => 'paid', 'total' => 9900, 'currency' => 'EUR']);
        $this->makeSubscriptionLine('order_item_1', 'ord_initial', 'subscription_orders');
        $this->makeSubscriptionLine('order_item_2', 'ord_renewal', 'subscription_orders');

        // An order with a one-off line must NOT associate.
        Order::create(['vatly_id' => 'ord_one_off', 'status' => 'paid', 'total' => 4900, 'currency' => 'EUR']);
        OrderLine::create([
            'vatly_id' => 'order_item_oneoff',
            'order_vatly_id' => 'ord_one_off',
            'description' => 'One-off',
            'quantity' => 1,
            'base_price' => 4900,
            'total' => 4900,
            'subtotal' => 4050,
            'product_type' => 'one_off_product',
            'product_id' => 'subscription_orders', // same id value, wrong type — must not leak
        ]);

        // An order for a different subscription must NOT associate.
        Order::create(['vatly_id' => 'ord_other_sub', 'status' => 'paid', 'total' => 1000, 'currency' => 'EUR']);
        $this->makeSubscriptionLine('order_item_other', 'ord_other_sub', 'subscription_other');

        $orders = $subscription->orders;

        $this->assertCount(2, $orders);
        $this->assertEqualsCanonicalizing(
            [$initial->getVatlyId(), $renewal->getVatlyId()],
            $orders->map(fn ($o) => $o->getVatlyId())->all(),
        );
    }

    private function makeSubscriptionLine(string $vatlyId, string $orderVatlyId, string $subscriptionId): OrderLine
    {
        return OrderLine::create([
            'vatly_id' => $vatlyId,
            'order_vatly_id' => $orderVatlyId,
            'description' => 'Subscription renewal',
            'quantity' => 1,
            'base_price' => 9900,
            'total' => 9900,
            'subtotal' => 8182,
            'product_type' => 'subscription',
            'product_id' => $subscriptionId,
        ]);
    }
}
